"""PyCharm run configurations for problems.

Shareable run configurations are plain XML under ``.idea/runConfigurations``;
PyCharm loads new files on the next project refresh, so ``lc new`` can drop one
in and the problem is runnable from the gutter without any manual setup.
"""

from __future__ import annotations

import re
from pathlib import Path

from lc import meta
from lc.paths import DIR_RE, ROOT, all_problems

RUN_CONFIGS = ROOT / ".idea" / "runConfigurations"
MODULE = "leetcode"
FOLDER = "Problems"
MARKER = "<!-- generated by `lc pycharm`; edits are overwritten -->"

TEMPLATE = """<component name="ProjectRunConfigurationManager">
  {marker}
  <configuration default="false" name="{name}" type="tests" factoryName="py.test"{folder}>
    <module name="{module}" />
    <option name="ENV_FILES" value="" />
    <option name="INTERPRETER_OPTIONS" value="" />
    <option name="PARENT_ENVS" value="true" />
    <envs>
      <env name="PYTHONUNBUFFERED" value="1" />
    </envs>
    <option name="SDK_HOME" value="" />
    <option name="WORKING_DIRECTORY" value="$PROJECT_DIR$" />
    <option name="IS_MODULE_SDK" value="true" />
    <option name="ADD_CONTENT_ROOTS" value="true" />
    <option name="ADD_SOURCE_ROOTS" value="true" />
    <option name="_new_keywords" value="&quot;&quot;" />
    <option name="_new_parameters" value="&quot;&quot;" />
    <option name="_new_additionalArguments" value="&quot;{args}&quot;" />
    <option name="_new_target" value="&quot;$PROJECT_DIR$/{target}&quot;" />
    <option name="_new_targetType" value="&quot;PATH&quot;" />
    <method v="2" />
  </configuration>
</component>
"""


def _filename(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_") + ".xml"


def _render(*, name: str, target: str, folder: str | None, args: str = "") -> str:
    return TEMPLATE.format(
        marker=MARKER,
        name=name,
        module=MODULE,
        target=target,
        args=args,
        folder=f' folderName="{folder}"' if folder else "",
    )


def config_name(problem: Path) -> str:
    number, slug = DIR_RE.match(problem.name).groups()
    title = meta.parse(problem / "README.md").get("title") or slug.replace("-", " ").title()
    return f"{int(number):04d} {title}"


def write(problem: Path) -> Path:
    """Write the pytest run configuration for one problem, overwriting any stale one."""
    RUN_CONFIGS.mkdir(parents=True, exist_ok=True)
    name = config_name(problem)
    path = RUN_CONFIGS / _filename(name)
    path.write_text(
        _render(
            name=name,
            target=problem.relative_to(ROOT).as_posix(),
            folder=FOLDER,
        )
    )
    return path


def sync() -> int:
    """Regenerate every generated configuration, dropping ones whose problem is gone."""
    RUN_CONFIGS.mkdir(parents=True, exist_ok=True)
    keep = {_filename("All problems")}
    (RUN_CONFIGS / _filename("All problems")).write_text(
        _render(name="All problems", target="problems", folder=None)
    )
    for problem in all_problems():
        keep.add(write(problem).name)
    removed = 0
    for path in RUN_CONFIGS.glob("*.xml"):
        # only ever delete our own output, never a hand-made configuration
        if path.name not in keep and MARKER in path.read_text():
            path.unlink()
            removed += 1
    print(f"wrote {len(keep)} run configurations" + (f", removed {removed}" if removed else ""))
    return 0
