"""Cases for 24. Swap Nodes in Pairs.

Lists are written the way LeetCode writes them; ``NORMALIZE`` turns whatever a
solution returns — a node chain or ``None`` — back into that bracket form.

The statement forbids modifying node *values*, and comparing values cannot
detect that: a solution that swaps ``val`` fields produces the same output as
one that relinks nodes. The last two cases check node identity instead, which
is the only way to tell them apart.
"""

from __future__ import annotations

from typing import Any

from lc.harness import check, load_solutions

SOLUTIONS = load_solutions(__file__)


class ListNode:
    def __init__(self, val: int = 0, next: ListNode | None = None):
        self.val = val
        self.next = next

    def __repr__(self) -> str:
        return f"linked_list({NORMALIZE(self)})"


def linked_list(values: list[int]) -> ListNode | None:
    head = None
    for value in reversed(values):
        head = ListNode(value, head)
    return head


def NORMALIZE(value: Any) -> list[int]:
    if isinstance(value, list):
        return value
    values = []
    node = value
    while node is not None:
        values.append(node.val)
        node = node.next
    return values


def relinked(expected: list[int]):
    """The answer, plus proof that nodes moved rather than values.

    A correct solution returns the node that was second, and the node that was
    the head ends up right behind it. A solution that swaps ``val`` fields
    returns the original head object, and fails this.
    """

    def validate(actual: Any, head: Any) -> bool:
        return NORMALIZE(actual) == expected and actual is not head and actual.next is head

    return validate


CASES = [
    ((linked_list([1, 2, 3, 4]),), [2, 1, 4, 3]),
    ((linked_list([]),), []),
    ((linked_list([1]),), [1]),
    ((linked_list([1, 2, 3]),), [2, 1, 3]),
    ((linked_list([1, 2]),), [2, 1]),
    ((linked_list([7, 7, 7, 7]),), [7, 7, 7, 7]),
    ((linked_list([0, 100]),), [100, 0]),
    ((linked_list([0, 0, 100, 100, 50]),), [0, 0, 100, 100, 50]),
    (
        (
            linked_list(
                [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    32,
                    33,
                    34,
                    35,
                    36,
                    37,
                    38,
                    39,
                    40,
                    41,
                    42,
                    43,
                    44,
                    45,
                    46,
                    47,
                    48,
                    49,
                    50,
                    51,
                    52,
                    53,
                    54,
                    55,
                    56,
                    57,
                    58,
                    59,
                    60,
                    61,
                    62,
                    63,
                    64,
                    65,
                    66,
                    67,
                    68,
                    69,
                    70,
                    71,
                    72,
                    73,
                    74,
                    75,
                    76,
                    77,
                    78,
                    79,
                    80,
                    81,
                    82,
                    83,
                    84,
                    85,
                    86,
                    87,
                    88,
                    89,
                    90,
                    91,
                    92,
                    93,
                    94,
                    95,
                    96,
                    97,
                    98,
                    99,
                ]
            ),
        ),
        [
            1,
            0,
            3,
            2,
            5,
            4,
            7,
            6,
            9,
            8,
            11,
            10,
            13,
            12,
            15,
            14,
            17,
            16,
            19,
            18,
            21,
            20,
            23,
            22,
            25,
            24,
            27,
            26,
            29,
            28,
            31,
            30,
            33,
            32,
            35,
            34,
            37,
            36,
            39,
            38,
            41,
            40,
            43,
            42,
            45,
            44,
            47,
            46,
            49,
            48,
            51,
            50,
            53,
            52,
            55,
            54,
            57,
            56,
            59,
            58,
            61,
            60,
            63,
            62,
            65,
            64,
            67,
            66,
            69,
            68,
            71,
            70,
            73,
            72,
            75,
            74,
            77,
            76,
            79,
            78,
            81,
            80,
            83,
            82,
            85,
            84,
            87,
            86,
            89,
            88,
            91,
            90,
            93,
            92,
            95,
            94,
            97,
            96,
            99,
            98,
        ],
    ),
    (
        (
            linked_list(
                [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    32,
                    33,
                    34,
                    35,
                    36,
                    37,
                    38,
                    39,
                    40,
                    41,
                    42,
                    43,
                    44,
                    45,
                    46,
                    47,
                    48,
                    49,
                    50,
                    51,
                    52,
                    53,
                    54,
                    55,
                    56,
                    57,
                    58,
                    59,
                    60,
                    61,
                    62,
                    63,
                    64,
                    65,
                    66,
                    67,
                    68,
                    69,
                    70,
                    71,
                    72,
                    73,
                    74,
                    75,
                    76,
                    77,
                    78,
                    79,
                    80,
                    81,
                    82,
                    83,
                    84,
                    85,
                    86,
                    87,
                    88,
                    89,
                    90,
                    91,
                    92,
                    93,
                    94,
                    95,
                    96,
                    97,
                    98,
                ]
            ),
        ),
        [
            1,
            0,
            3,
            2,
            5,
            4,
            7,
            6,
            9,
            8,
            11,
            10,
            13,
            12,
            15,
            14,
            17,
            16,
            19,
            18,
            21,
            20,
            23,
            22,
            25,
            24,
            27,
            26,
            29,
            28,
            31,
            30,
            33,
            32,
            35,
            34,
            37,
            36,
            39,
            38,
            41,
            40,
            43,
            42,
            45,
            44,
            47,
            46,
            49,
            48,
            51,
            50,
            53,
            52,
            55,
            54,
            57,
            56,
            59,
            58,
            61,
            60,
            63,
            62,
            65,
            64,
            67,
            66,
            69,
            68,
            71,
            70,
            73,
            72,
            75,
            74,
            77,
            76,
            79,
            78,
            81,
            80,
            83,
            82,
            85,
            84,
            87,
            86,
            89,
            88,
            91,
            90,
            93,
            92,
            95,
            94,
            97,
            96,
            98,
        ],
    ),
    ((linked_list([1, 2]),), relinked([2, 1])),
    ((linked_list([1, 2, 3, 4]),), relinked([2, 1, 4, 3])),
]


def test_solution(solution, case, equal):
    check(solution, case, equal)
