"""Cases for 21. Merge Two Sorted Lists.

Lists are written the way LeetCode writes them and built by ``linked_list``;
``NORMALIZE`` turns whatever a solution returns — a node chain or ``None`` —
back into that bracket form, so a failure shows two lists rather than two
object addresses.
"""

from __future__ import annotations

from typing import Any

from lc.harness import check, load_solutions

SOLUTIONS = load_solutions(__file__)


class ListNode:
    def __init__(self, val: int = 0, next: ListNode | None = None):
        self.val = val
        self.next = next

    def __repr__(self) -> str:
        return f"linked_list({NORMALIZE(self)})"


def linked_list(values: list[int]) -> ListNode | None:
    head = None
    for value in reversed(values):
        head = ListNode(value, head)
    return head


def NORMALIZE(value: Any) -> list[int]:
    if isinstance(value, list):
        return value
    values = []
    node = value
    while node is not None:
        values.append(node.val)
        node = node.next
    return values


CASES = [
    ((linked_list([1, 2, 4]), linked_list([1, 3, 4])), [1, 1, 2, 3, 4, 4]),
    ((linked_list([]), linked_list([])), []),
    ((linked_list([]), linked_list([0])), [0]),
    ((linked_list([0]), linked_list([])), [0]),
    ((linked_list([1]), linked_list([1])), [1, 1]),
    ((linked_list([1, 1, 1]), linked_list([1, 1])), [1, 1, 1, 1, 1]),
    ((linked_list([-100, 0, 100]), linked_list([-100, 100])), [-100, -100, 0, 100, 100]),
    ((linked_list([1, 2, 3]), linked_list([4, 5, 6])), [1, 2, 3, 4, 5, 6]),
    ((linked_list([4, 5, 6]), linked_list([1, 2, 3])), [1, 2, 3, 4, 5, 6]),
    ((linked_list([2]), linked_list([1, 3, 5, 7, 9])), [1, 2, 3, 5, 7, 9]),
    (
        (
            linked_list(
                [
                    0,
                    2,
                    4,
                    6,
                    8,
                    10,
                    12,
                    14,
                    16,
                    18,
                    20,
                    22,
                    24,
                    26,
                    28,
                    30,
                    32,
                    34,
                    36,
                    38,
                    40,
                    42,
                    44,
                    46,
                    48,
                    50,
                    52,
                    54,
                    56,
                    58,
                    60,
                    62,
                    64,
                    66,
                    68,
                    70,
                    72,
                    74,
                    76,
                    78,
                    80,
                    82,
                    84,
                    86,
                    88,
                    90,
                    92,
                    94,
                    96,
                    98,
                ]
            ),
            linked_list(
                [
                    1,
                    3,
                    5,
                    7,
                    9,
                    11,
                    13,
                    15,
                    17,
                    19,
                    21,
                    23,
                    25,
                    27,
                    29,
                    31,
                    33,
                    35,
                    37,
                    39,
                    41,
                    43,
                    45,
                    47,
                    49,
                    51,
                    53,
                    55,
                    57,
                    59,
                    61,
                    63,
                    65,
                    67,
                    69,
                    71,
                    73,
                    75,
                    77,
                    79,
                    81,
                    83,
                    85,
                    87,
                    89,
                    91,
                    93,
                    95,
                    97,
                    99,
                ]
            ),
        ),
        [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
            81,
            82,
            83,
            84,
            85,
            86,
            87,
            88,
            89,
            90,
            91,
            92,
            93,
            94,
            95,
            96,
            97,
            98,
            99,
        ],
    ),
    (
        (
            linked_list(
                [
                    -100,
                    -99,
                    -98,
                    -97,
                    -96,
                    -95,
                    -94,
                    -93,
                    -92,
                    -91,
                    -90,
                    -89,
                    -88,
                    -87,
                    -86,
                    -85,
                    -84,
                    -83,
                    -82,
                    -81,
                    -80,
                    -79,
                    -78,
                    -77,
                    -76,
                    -75,
                    -74,
                    -73,
                    -72,
                    -71,
                    -70,
                    -69,
                    -68,
                    -67,
                    -66,
                    -65,
                    -64,
                    -63,
                    -62,
                    -61,
                    -60,
                    -59,
                    -58,
                    -57,
                    -56,
                    -55,
                    -54,
                    -53,
                    -52,
                    -51,
                ]
            ),
            linked_list(
                [
                    50,
                    51,
                    52,
                    53,
                    54,
                    55,
                    56,
                    57,
                    58,
                    59,
                    60,
                    61,
                    62,
                    63,
                    64,
                    65,
                    66,
                    67,
                    68,
                    69,
                    70,
                    71,
                    72,
                    73,
                    74,
                    75,
                    76,
                    77,
                    78,
                    79,
                    80,
                    81,
                    82,
                    83,
                    84,
                    85,
                    86,
                    87,
                    88,
                    89,
                    90,
                    91,
                    92,
                    93,
                    94,
                    95,
                    96,
                    97,
                    98,
                    99,
                ]
            ),
        ),
        [
            -100,
            -99,
            -98,
            -97,
            -96,
            -95,
            -94,
            -93,
            -92,
            -91,
            -90,
            -89,
            -88,
            -87,
            -86,
            -85,
            -84,
            -83,
            -82,
            -81,
            -80,
            -79,
            -78,
            -77,
            -76,
            -75,
            -74,
            -73,
            -72,
            -71,
            -70,
            -69,
            -68,
            -67,
            -66,
            -65,
            -64,
            -63,
            -62,
            -61,
            -60,
            -59,
            -58,
            -57,
            -56,
            -55,
            -54,
            -53,
            -52,
            -51,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
            81,
            82,
            83,
            84,
            85,
            86,
            87,
            88,
            89,
            90,
            91,
            92,
            93,
            94,
            95,
            96,
            97,
            98,
            99,
        ],
    ),
]


def test_solution(solution, case, equal):
    check(solution, case, equal)
